# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LintmaxGo < Formula
  desc "Maximum-strictness Go quality gate. Always-latest, never stale."
  homepage "https://github.com/1qh/lintmax-go"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/1qh/lintmax-go/releases/download/v0.6.1/lintmax-go_0.6.1_darwin_amd64.tar.gz"
      sha256 "dccaf593d26f439174b306081a4d5797975f836d16f75b62029a11cc681a4f6b"

      define_method(:install) do
        bin.install "lintmax-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/1qh/lintmax-go/releases/download/v0.6.1/lintmax-go_0.6.1_darwin_arm64.tar.gz"
      sha256 "3821490ae4889921fcdca73db12051e5ca0b3b0cc7a1d7ff7c8db576751daef9"

      define_method(:install) do
        bin.install "lintmax-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/1qh/lintmax-go/releases/download/v0.6.1/lintmax-go_0.6.1_linux_amd64.tar.gz"
      sha256 "aa52c7a44e71271380a25110bdd76e98797efd73f5715aabab7706079a44e2ca"
      define_method(:install) do
        bin.install "lintmax-go"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/1qh/lintmax-go/releases/download/v0.6.1/lintmax-go_0.6.1_linux_arm64.tar.gz"
      sha256 "4f65e6891a50d7ce34de0c81c7e3ca3b1c154ccd1973e0e2c6c9f2c44d316c06"
      define_method(:install) do
        bin.install "lintmax-go"
      end
    end
  end
end
