# This file was generated by GoReleaser. DO NOT EDIT.
cask "lintmax-go" do
  version "0.6.2"

  on_macos do
    on_intel do
      sha256 "beca5da936eadf57fb2cb74d9c4e751571296cd5b5a37d5a7cf9c03fc657783c"
      url "https://github.com/1qh/lintmax-go/releases/download/v#{version}/lintmax-go_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9c99b06246df79c2c9e5ca435cedb1c65e6d1dc21d53565969db3839dc9a3627"
      url "https://github.com/1qh/lintmax-go/releases/download/v#{version}/lintmax-go_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "34b7057932ab661167d48e56ea00c9ac93d2dd39406de6293ecf70f00243136e"
      url "https://github.com/1qh/lintmax-go/releases/download/v#{version}/lintmax-go_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f21313f117dd0ce36ec89d9ad7b51fec989100c17f83c8136fa2b542ee1b5a5c"
      url "https://github.com/1qh/lintmax-go/releases/download/v#{version}/lintmax-go_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lintmax-go"
  desc "Maximum-strictness Go quality gate. Always-latest, never stale."
  homepage "https://github.com/1qh/lintmax-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lintmax-go"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lintmax-go"]
    end
  end

  # No zap stanza required

end
