# This file was generated by GoReleaser. DO NOT EDIT.
cask "lintmax-go" do
  version "0.17.0"

  on_macos do
    on_intel do
      sha256 "a8608d470b9d402a17b16184b769f6d57b9e70cf6ef62b87011d727b1e81c44d"
      url "https://github.com/1qh/lintmax-go/releases/download/v#{version}/lintmax-go_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9565bd43bee8d48d10f0549aca6341dccc9af6f603865851854a8591bf245ce1"
      url "https://github.com/1qh/lintmax-go/releases/download/v#{version}/lintmax-go_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8f53e206847346bd41910f2f99ac88490b01a694938a5a578b65ef1233966dbf"
      url "https://github.com/1qh/lintmax-go/releases/download/v#{version}/lintmax-go_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0e9b9c22d1d67ede6543bb71bfbf6d26523a8c14267876c47549210ff3cb9399"
      url "https://github.com/1qh/lintmax-go/releases/download/v#{version}/lintmax-go_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lintmax-go"
  desc "Maximum-strictness Go quality gate. Always-latest, never stale."
  homepage "https://github.com/1qh/lintmax-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lintmax-go"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lintmax-go"]
    end
  end

  # No zap stanza required

end
