# This file was generated by GoReleaser. DO NOT EDIT.
cask "lintmax-go" do
  version "0.19.0"

  on_macos do
    on_intel do
      sha256 "7a683f4ad5fefaa28a98669b4a1aa38dba1a35730ae519d3612f08fc31828e7e"
      url "https://github.com/1qh/lintmax-go/releases/download/v#{version}/lintmax-go_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f95528039989416078e55ecd3d36e209968e2b41ba34abf88164ecfac3ab5219"
      url "https://github.com/1qh/lintmax-go/releases/download/v#{version}/lintmax-go_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "821761356ded6b95445d22ec856d76ac757c68b2c068b72fbec914979f737490"
      url "https://github.com/1qh/lintmax-go/releases/download/v#{version}/lintmax-go_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5465e2ff12e177135757c37341119e8fe218c9595af10bd3e748aa8f83f1fb69"
      url "https://github.com/1qh/lintmax-go/releases/download/v#{version}/lintmax-go_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lintmax-go"
  desc "Maximum-strictness Go quality gate. Always-latest, never stale."
  homepage "https://github.com/1qh/lintmax-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lintmax-go"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lintmax-go"]
    end
  end

  # No zap stanza required

end
